### ISSUE TITLE
RuntimeError: Environment went away

### ISSUE THREAD

**Issue by mountainash** [CamilionEU/lektor-git-src-publisher#2] opened 2019-12-17 09:52 UTC
Running Lektor 3.1.3 with version 0.1 of this projects package running in a Docker container (python:3.7). Installed using pip3 from a requirements.txt. Loading `lektor server -v -h 0.0.0.0` from within the same directory as the `.lektorproject` file causes the following error repeatedly when trying to pull or push a site using this package.
```python
Debugging middleware caught exception in streamed response at a point where response headers were already sent.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/lektor/admin/utils.py", line 18, in generate
    for event in chain(f(*args, **kwargs), (None,)):
  File "/usr/local/lib/python3.7/site-packages/lektor/admin/modules/api.py", line 315, in generator
    for event in event_iter:
  File "/usr/local/lib/python3.7/site-packages/lektor_git_src_publisher.py", line 121, in publish
    for line in self._git(["add", "."]).output:
  File "/usr/local/lib/python3.7/site-packages/lektor_git_src_publisher.py", line 17, in _git
    root_path = self._plugin.env.root_path
  File "/usr/local/lib/python3.7/site-packages/lektor/pluginsystem.py", line 40, in env
    raise RuntimeError('Environment went away')
RuntimeError: Environment went away
```

I've created a [the first] pull request #1 to a change that fixes this issue.

**Comment by evilham** [comment] 2020-08-13 08:09
Reopening because of: https://github.com/CamilionEU/lektor-git-src-publisher/pull/1#issuecomment-673328200

I think this might be it:

> This is still an issue. Could it also be that the {sitename}.lektorproject file isn't at the root of the git project (it's 2 levels deeper).

Booking some time to look into it, thank you.

**Comment by evilham** [comment] 2020-08-13 08:14
@mountainash further question because I think it can be relevant: are you using `inotify`? (answer is most likely yes if you are using Linux)

**Comment by mountainash** [comment] 2020-08-13 08:32
Yes... but not directly (but to Lektor, yes).

I'll explain (as this might be helpful for other Lektor/Mac users) - Lektor is running in a `python:3.8` Docker container on macOS. The image is set with the `GIT_DISCOVERY_ACROSS_FILESYSTEM=1` flag. I also use http://docker-sync.io/ to speed up Lektor, as Docker + Compose on Mac's filesystem has speed issues which are very, very noticeable when building the Lektor source on a 100+ page site in 3 languages ("alternatives") (as it does to read/write every file on startup of `lektor server`). Using `docker-sync` the build completes in a third of the time, and thats even compared to the using these options in regular Compose:
```yml
    volumes:
      - type: bind
        source: .
        target: /lektor/
        volume:
          nocopy: true
        consistency: delegated
```

But I've ran Lektor with `v0.2.1` **without** docker-sync and the same error occurs.

**Comment by evilham** [comment] 2020-08-13 11:39
@mountainash would you mind providing some more information about how you are running lektor?

Specifically:
1. What is the working directory, relative to the `.lektorproject` file.
2. What does the command line look like? (e.g. are you using `--project`?)

I am having issues reproducing the error, even under a Linux system with `inotify` and a project whose `.lektorproject` is not at the root of the git repository.
Your change has very ugly unintended consequences when the `--project` flag is used, so we can't address it with #6

**Comment by evilham** [comment] 2020-08-13 12:00
I *think* your issue is fixed in the `develop` branch. Would you mind testing that?
Remember you can use `pip install -e PATH_TO_SOURCE` to run checked out code.

**Comment by mountainash** [comment] 2020-08-13 12:31
Thanks for looking into this.

Lektor is ran with `lektor server -v -h 0.0.0.0 -f scss -f minify:html,js` with a working directory at `/srv/lektor/src/`. `/src/` contains the `.lektorproject` and `/srv` is the git root.

I'll re-build with your "dev" changes soon and report back. Also, a FYI, you can just add `https://github.com/CamilionEU/lektor-git-src-publisher/archive/develop.zip` to your `requirements.txt` without the need to even checkout (which is what's happening in the Docker setup).

**Comment by mountainash** [comment] 2020-08-17 08:56
Just built and tested against the `develop` branch; I get the same `Environment went away` error.

**Comment by evilham** [comment] 2020-08-17 09:25
:woman_facepalming: just realised I've been misreading your stack trace:
```
lektor_1  |   File "/usr/local/lib/python3.8/site-packages/lektor_git_src_publisher.py", line 18, in _git
lektor_1  |     root_path = self._plugin.env.root_path
lektor_1  |   File "/usr/local/lib/python3.8/site-packages/lektor/pluginsystem.py", line 40, in env
lektor_1  |     raise RuntimeError('Environment went away')
lektor_1  | RuntimeError: Environment went away
```

The exception gets raised when trying to access the environment `root_path` :-D so, "obviously" the fix in develop won't work. 
Good thing that's clear now though, will ping you with another iteration soon.

**Comment by evilham** [comment] 2020-08-17 09:40
@mountainash please give it another go from the `develop` branch.

**Comment by mountainash** [comment] 2020-08-17 14:05
@evilham I can confirm that the [latest changes](https://github.com/CamilionEU/lektor-git-src-publisher/commit/2dea766d0a5d5af2e2aefb09efb3efe43260358f) on `develop` are working for my setup.

**Closed as completed** 2020-08-17 14:17 UTC
